### ISSUE TITLE
Member Didn't Agree to Challenge Terms

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-payment-tool#19]
I'm paying out users for a completed Marathon Match. Apparently the terms they agree to are different than those that direct needs for challenges.

I've submitted a payment for user `now_you_see`, who has not agreed to terms. The payment tool just hangs on "Drafting Payment" and never comes back. The challenge is created in direct, but the member is not assigned (obviously) so it's just frozen.

Adding the user in direct shows this error:
![screen shot 2018-09-05 at 1 54 55 pm](https://user-images.githubusercontent.com/5400156/45112981-251fb800-b117-11e8-8f7e-b9a56d9d953f.png)

The UI should, on this error, come back and say the error to the user, not just hang out there.

**Comment by cwdcwd** [comment]
So I'm not sure if the API gives back the error details to handle verbosely but the App should not just hang out like it does when there's an error. We need some graceful error handling put in around this and #16. I think the latter case is a known issue with the challenge API creating and activating a challenge but, again, we should field any API error responses or timeouts appropriately.
@birdofpreyru thoughts?

**Comment by birdofpreyru** [comment]
@cwdcwd yeah, it turns out that the error-messaging setup of **community-app** was not correctly reproduced in *topcoder-payment-tool* when it was spawned out, so error messages were not shown in UI. I fixed this and released to development environment. Though, at the moment it does not tell about precise errors, just shows the modal saying smth like _It did not work out, please finalize via Direct, or contact Topcoder support_.  By the way, **develop** contains a bunch of other updates that were never put to production.
